apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tenant-operator.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "tenant-operator.labels" . | nindent 4 }}
