apiVersion: v1
kind: Service
metadata:
  name: {{ include "tenant-operator.fullname" . }}-webhook
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "tenant-operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "tenant-operator.selectorLabels" . | nindent 4 }}
  ports:
  - name: webhook
    port: {{ .Values.webhooks.service.port }}
    targetPort: {{ .Values.webhooks.service.targetPort }}
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tenant-operator.fullname" . }}-metrics
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "tenant-operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "tenant-operator.selectorLabels" . | nindent 4 }}
  ports:
  - name: metrics
    port: {{ .Values.metrics.port }}
    targetPort: {{ .Values.metrics.port }}
    protocol: TCP
